name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        nodejs: ['10', '12', '14', '16']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Report coverage
        run: npm run codecov

  lint:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install NPM dependencies
        run: npm ci
      - name: Check version
        run: npm run version:check
      - name: Lint code
        run: npm run lint
      - name: Lint commits
        run: npm run lint:commits

  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install NPM dependencies
        run: npm ci
      - name: Build
        run: npm run compile
